/**
 * This file contains a constant object `IMG_PATHS` that holds the paths to various images used in the game. The object is frozen to prevent any modifications to its properties.
 */
const IMG_PATHS = Object.freeze({
    character: {
        swim: [
            "assets/img/character/swim/1.png",
            "assets/img/character/swim/2.png",
            "assets/img/character/swim/3.png",
            "assets/img/character/swim/4.png",
            "assets/img/character/swim/5.png",
            "assets/img/character/swim/6.png",
        ],
        hurt: {
            shock: [
                "assets/img/character/hurt/shock/1.png",
                "assets/img/character/hurt/shock/2.png",
            ],
            poison: [
                "assets/img/character/hurt/poison/1.png",
                "assets/img/character/hurt/poison/2.png",
                "assets/img/character/hurt/poison/3.png",
                "assets/img/character/hurt/poison/4.png",
            ],
        },
        dead: {
            poison: [
                "assets/img/character/dead/poison/1.png",
                "assets/img/character/dead/poison/2.png",
                "assets/img/character/dead/poison/3.png",
                "assets/img/character/dead/poison/4.png",
                "assets/img/character/dead/poison/5.png",
                "assets/img/character/dead/poison/6.png",
                "assets/img/character/dead/poison/7.png",
                "assets/img/character/dead/poison/8.png",
                "assets/img/character/dead/poison/9.png",
                "assets/img/character/dead/poison/10.png",
                "assets/img/character/dead/poison/11.png",
                "assets/img/character/dead/poison/12.png",
            ],
            shock: [
                "assets/img/character/dead/shock/1.png",
                "assets/img/character/dead/shock/2.png",
                "assets/img/character/dead/shock/3.png",
                "assets/img/character/dead/shock/4.png",
                "assets/img/character/dead/shock/5.png",
                "assets/img/character/dead/shock/6.png",
                "assets/img/character/dead/shock/7.png",
                "assets/img/character/dead/shock/8.png",
                "assets/img/character/dead/shock/9.png",
                "assets/img/character/dead/shock/10.png",
            ],
        },
        idle: [
            "assets/img/character/idle/1.png",
            "assets/img/character/idle/2.png",
            "assets/img/character/idle/3.png",
            "assets/img/character/idle/4.png",
            "assets/img/character/idle/5.png",
            "assets/img/character/idle/6.png",
            "assets/img/character/idle/7.png",
            "assets/img/character/idle/8.png",
            "assets/img/character/idle/9.png",
            "assets/img/character/idle/10.png",
            "assets/img/character/idle/11.png",
            "assets/img/character/idle/12.png",
            "assets/img/character/idle/13.png",
            "assets/img/character/idle/14.png",
            "assets/img/character/idle/15.png",
            "assets/img/character/idle/16.png",
            "assets/img/character/idle/17.png",
            "assets/img/character/idle/18.png",
        ],
        sleep: [
            "assets/img/character/sleep/1.png",
            "assets/img/character/sleep/2.png",
            "assets/img/character/sleep/3.png",
            "assets/img/character/sleep/4.png",
            "assets/img/character/sleep/5.png",
            "assets/img/character/sleep/6.png",
            "assets/img/character/sleep/7.png",
            "assets/img/character/sleep/8.png",
            "assets/img/character/sleep/9.png",
            "assets/img/character/sleep/10.png",
            "assets/img/character/sleep/11.png",
            "assets/img/character/sleep/12.png",
            "assets/img/character/sleep/13.png",
            "assets/img/character/sleep/14.png",
        ],
        attack: {
            slap: [
                "assets/img/character/attack/slap/1.png",
                "assets/img/character/attack/slap/2.png",
                "assets/img/character/attack/slap/3.png",
                "assets/img/character/attack/slap/4.png",
                "assets/img/character/attack/slap/5.png",
                "assets/img/character/attack/slap/6.png",
                "assets/img/character/attack/slap/7.png",
                "assets/img/character/attack/slap/8.png",
            ],
            bubble: {
                normal: [
                    "assets/img/character/attack/bubble/normal/1.png",
                    "assets/img/character/attack/bubble/normal/2.png",
                    "assets/img/character/attack/bubble/normal/3.png",
                    "assets/img/character/attack/bubble/normal/4.png",
                    "assets/img/character/attack/bubble/normal/5.png",
                    "assets/img/character/attack/bubble/normal/6.png",
                    "assets/img/character/attack/bubble/normal/7.png",
                    "assets/img/character/attack/bubble/normal/8.png",
                ],
                poison: [
                    "assets/img/character/attack/bubble/poison/1.png",
                    "assets/img/character/attack/bubble/poison/2.png",
                    "assets/img/character/attack/bubble/poison/3.png",
                    "assets/img/character/attack/bubble/poison/4.png",
                    "assets/img/character/attack/bubble/poison/5.png",
                    "assets/img/character/attack/bubble/poison/6.png",
                    "assets/img/character/attack/bubble/poison/7.png",
                    "assets/img/character/attack/bubble/poison/8.png",
                ],
            },
        },
    },

    bubble: {
        normal: "assets/img/character/bubble/normal/1.png",
        poison: "assets/img/character/bubble/poison/1.png",
    },

    coin: "assets/img/collectibles/coin/1.png",

    poisonBottle: {
        left: "assets/img/collectibles/poison-bottle/left/1.png",
        right: "assets/img/collectibles/poison-bottle/right/1.png",
    },

    puffer: {
        swim: [
            "assets/img/enemies/regular-enemies/puffer/swim/1.png",
            "assets/img/enemies/regular-enemies/puffer/swim/2.png",
            "assets/img/enemies/regular-enemies/puffer/swim/3.png",
            "assets/img/enemies/regular-enemies/puffer/swim/4.png",
        ],
        dead: "assets/img/enemies/regular-enemies/puffer/dead/1.png",
        transition: [
            "assets/img/enemies/regular-enemies/puffer/transition/1.png",
            "assets/img/enemies/regular-enemies/puffer/transition/2.png",
            "assets/img/enemies/regular-enemies/puffer/transition/3.png",
            "assets/img/enemies/regular-enemies/puffer/transition/4.png",
            "assets/img/enemies/regular-enemies/puffer/transition/5.png",
        ],
        bubbleSwim: [
            "assets/img/enemies/regular-enemies/puffer/bubble-swim/1.png",
            "assets/img/enemies/regular-enemies/puffer/bubble-swim/2.png",
            "assets/img/enemies/regular-enemies/puffer/bubble-swim/3.png",
            "assets/img/enemies/regular-enemies/puffer/bubble-swim/4.png",
            "assets/img/enemies/regular-enemies/puffer/bubble-swim/5.png",
        ],
    },

    jellyFish: {
        swim: [
            "assets/img/enemies/regular-enemies/jelly-fish/swim/1.png",
            "assets/img/enemies/regular-enemies/jelly-fish/swim/2.png",
            "assets/img/enemies/regular-enemies/jelly-fish/swim/3.png",
            "assets/img/enemies/regular-enemies/jelly-fish/swim/4.png",
        ],
        dead: [
            "assets/img/enemies/regular-enemies/jelly-fish/dead/1.png",
            "assets/img/enemies/regular-enemies/jelly-fish/dead/2.png",
            "assets/img/enemies/regular-enemies/jelly-fish/dead/3.png",
            "assets/img/enemies/regular-enemies/jelly-fish/dead/4.png",
        ],
    },

    endboss: {
        orca: {
            swim: [
                "assets/img/enemies/endboss/orca/swim/1.png",
                "assets/img/enemies/endboss/orca/swim/2.png",
                "assets/img/enemies/endboss/orca/swim/3.png",
                "assets/img/enemies/endboss/orca/swim/4.png",
                "assets/img/enemies/endboss/orca/swim/5.png",
                "assets/img/enemies/endboss/orca/swim/6.png",
                "assets/img/enemies/endboss/orca/swim/7.png",
                "assets/img/enemies/endboss/orca/swim/8.png",
                "assets/img/enemies/endboss/orca/swim/9.png",
                "assets/img/enemies/endboss/orca/swim/10.png",
                "assets/img/enemies/endboss/orca/swim/11.png",
                "assets/img/enemies/endboss/orca/swim/12.png",
                "assets/img/enemies/endboss/orca/swim/13.png",
            ],
            apear: [
                "assets/img/enemies/endboss/orca/apear/1.png",
                "assets/img/enemies/endboss/orca/apear/2.png",
                "assets/img/enemies/endboss/orca/apear/3.png",
                "assets/img/enemies/endboss/orca/apear/4.png",
                "assets/img/enemies/endboss/orca/apear/5.png",
                "assets/img/enemies/endboss/orca/apear/6.png",
                "assets/img/enemies/endboss/orca/apear/7.png",
                "assets/img/enemies/endboss/orca/apear/8.png",
                "assets/img/enemies/endboss/orca/apear/9.png",
                "assets/img/enemies/endboss/orca/apear/10.png",
            ],
            attack: [
                "assets/img/enemies/endboss/orca/attack/1.png",
                "assets/img/enemies/endboss/orca/attack/2.png",
                "assets/img/enemies/endboss/orca/attack/3.png",
                "assets/img/enemies/endboss/orca/attack/4.png",
                "assets/img/enemies/endboss/orca/attack/5.png",
                "assets/img/enemies/endboss/orca/attack/6.png",
            ],
            hurt: [
                "assets/img/enemies/endboss/orca/hurt/1.png",
                "assets/img/enemies/endboss/orca/hurt/2.png",
                "assets/img/enemies/endboss/orca/hurt/3.png",
                "assets/img/enemies/endboss/orca/hurt/4.png",
            ],
            dead: [
                "assets/img/enemies/endboss/orca/dead/1.png",
                "assets/img/enemies/endboss/orca/dead/2.png",
                "assets/img/enemies/endboss/orca/dead/3.png",
                "assets/img/enemies/endboss/orca/dead/4.png",
                "assets/img/enemies/endboss/orca/dead/5.png",
            ],
        },
    },

    hud: {
        poison: "assets/img/ui/poison/1.png",
        coin: "assets/img/ui/coin/1.png",
        lifebar: [
            "assets/img/ui/life/100.png",
            "assets/img/ui/life/80.png",
            "assets/img/ui/life/60.png",
            "assets/img/ui/life/40.png",
            "assets/img/ui/life/20.png",
            "assets/img/ui/life/0.png",
        ],
    },
});
