/**
 * This file contains a constant object `IMG_PATHS` that holds the paths to various images used in the game. The object is frozen to prevent any modifications to its properties.
 */
const IMG_PATHS = Object.freeze({
    character: {
        swimming: [
            "assets/img/1.Sharkie/3.Swim/1.png",
            "assets/img/1.Sharkie/3.Swim/2.png",
            "assets/img/1.Sharkie/3.Swim/1.png",
            "assets/img/1.Sharkie/3.Swim/3.png",
            "assets/img/1.Sharkie/3.Swim/4.png",
            "assets/img/1.Sharkie/3.Swim/5.png",
            "assets/img/1.Sharkie/3.Swim/6.png",
        ],
        hurtShock: [
            "assets/img/1.Sharkie/5.Hurt/2.Electric shock/1.png",
            "assets/img/1.Sharkie/5.Hurt/2.Electric shock/2.png",
        ],
        hurtPoison: [
            "assets/img/1.Sharkie/5.Hurt/1.Poisoned/1.png",
            "assets/img/1.Sharkie/5.Hurt/1.Poisoned/2.png",
            "assets/img/1.Sharkie/5.Hurt/1.Poisoned/3.png",
            "assets/img/1.Sharkie/5.Hurt/1.Poisoned/4.png",
        ],
        poisonDeath: [
            "assets/img/1.Sharkie/6.dead/1.Poisoned/1.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/2.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/3.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/4.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/5.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/6.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/7.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/8.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/9.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/10.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/11.png",
            "assets/img/1.Sharkie/6.dead/1.Poisoned/12.png",
        ],
        shockDeath: [
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/1.png",
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/2.png",
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/3.png",
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/4.png",
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/5.png",
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/6.png",
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/7.png",
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/8.png",
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/9.png",
            "assets/img/1.Sharkie/6.dead/2.Electro_shock/10.png",
        ],
        wait: [
            "assets/img/1.Sharkie/1.IDLE/1.png",
            "assets/img/1.Sharkie/1.IDLE/2.png",
            "assets/img/1.Sharkie/1.IDLE/3.png",
            "assets/img/1.Sharkie/1.IDLE/4.png",
            "assets/img/1.Sharkie/1.IDLE/5.png",
            "assets/img/1.Sharkie/1.IDLE/6.png",
            "assets/img/1.Sharkie/1.IDLE/7.png",
            "assets/img/1.Sharkie/1.IDLE/8.png",
            "assets/img/1.Sharkie/1.IDLE/9.png",
            "assets/img/1.Sharkie/1.IDLE/10.png",
            "assets/img/1.Sharkie/1.IDLE/11.png",
            "assets/img/1.Sharkie/1.IDLE/12.png",
            "assets/img/1.Sharkie/1.IDLE/13.png",
            "assets/img/1.Sharkie/1.IDLE/14.png",
            "assets/img/1.Sharkie/1.IDLE/15.png",
            "assets/img/1.Sharkie/1.IDLE/16.png",
            "assets/img/1.Sharkie/1.IDLE/17.png",
            "assets/img/1.Sharkie/1.IDLE/18.png",
        ],
        sleep: [
            "assets/img/1.Sharkie/2.Long_IDLE/i1.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i2.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i3.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i4.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i5.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i6.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i7.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i8.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i9.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i10.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i11.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i12.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i13.png",
            "assets/img/1.Sharkie/2.Long_IDLE/i14.png",
        ],
        slap: [
            "assets/img/1.Sharkie/4.Attack/Fin slap/1.png",
            "assets/img/1.Sharkie/4.Attack/Fin slap/2.png",
            "assets/img/1.Sharkie/4.Attack/Fin slap/3.png",
            "assets/img/1.Sharkie/4.Attack/Fin slap/4.png",
            "assets/img/1.Sharkie/4.Attack/Fin slap/5.png",
            "assets/img/1.Sharkie/4.Attack/Fin slap/6.png",
            "assets/img/1.Sharkie/4.Attack/Fin slap/7.png",
            "assets/img/1.Sharkie/4.Attack/Fin slap/8.png",
        ],
        createBubble: [
            "assets/img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/1.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/2.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/3.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/4.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/5.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/6.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/7.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/op1 (with bubble formation)/8.png",
        ],
        createBubblePoison: [
            "assets/img/1.Sharkie/4.Attack/Bubble trap/For Whale/1.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/For Whale/2.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/For Whale/3.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/For Whale/4.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/For Whale/5.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/For Whale/6.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/For Whale/7.png",
            "assets/img/1.Sharkie/4.Attack/Bubble trap/For Whale/8.png",
        ],
    },

    bubble: {
        normal: "assets/img/1.Sharkie/4.Attack/Bubble trap/Bubble.png",
        poison: "assets/img/1.Sharkie/4.Attack/Bubble trap/Poisoned Bubble (for whale).png",
    },

    coin: {
        normal: "assets/img/4. Marcadores/1. Coins/1.png",
    },

    poisonBottle: {
        left: "assets/img/4. Marcadores/Posión/Dark - Left.png",
        right: "assets/img/4. Marcadores/Posión/Dark - Right.png",
    },

    puffer: {
        swimming: [
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim1.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim2.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim2.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim3.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/1.Swim/1.swim4.png",
        ],
        death: "assets/img/2.Enemy/1.Puffer fish (3 color options)/4.DIE/1.Dead 1 (can animate by going up).png",
        aggroTransition: [
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition1.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition2.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition3.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition4.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/2.transition/1.transition5.png",
        ],
        aggro: [
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim1.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim2.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim3.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim4.png",
            "assets/img/2.Enemy/1.Puffer fish (3 color options)/3.Bubbleeswim/1.bubbleswim5.png",
        ],
    },

    jellyFish: {
        swimming: [
            "assets/img/2.Enemy/2 Jelly fish/Súper dangerous/Pink 1.png",
            "assets/img/2.Enemy/2 Jelly fish/Súper dangerous/Pink 2.png",
            "assets/img/2.Enemy/2 Jelly fish/Súper dangerous/Pink 3.png",
            "assets/img/2.Enemy/2 Jelly fish/Súper dangerous/Pink 4.png",
        ],
        death: [
            "assets/img/2.Enemy/2 Jelly fish/Dead/Pink/P1.png",
            "assets/img/2.Enemy/2 Jelly fish/Dead/Pink/P2.png",
            "assets/img/2.Enemy/2 Jelly fish/Dead/Pink/P3.png",
            "assets/img/2.Enemy/2 Jelly fish/Dead/Pink/P4.png",
        ],
    },

    endboss: {
        swimming: [
            "assets/img/2.Enemy/3 Final Enemy/2.floating/1.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/2.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/3.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/4.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/5.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/6.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/7.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/8.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/9.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/10.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/11.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/12.png",
            "assets/img/2.Enemy/3 Final Enemy/2.floating/13.png",
        ],
        appear: [
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/1.png",
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/2.png",
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/3.png",
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/4.png",
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/5.png",
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/6.png",
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/7.png",
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/8.png",
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/9.png",
            "assets/img/2.Enemy/3 Final Enemy/1.Introduce/10.png",
        ],
        attack: [
            "assets/img/2.Enemy/3 Final Enemy/Attack/1.png",
            "assets/img/2.Enemy/3 Final Enemy/Attack/2.png",
            "assets/img/2.Enemy/3 Final Enemy/Attack/3.png",
            "assets/img/2.Enemy/3 Final Enemy/Attack/4.png",
            "assets/img/2.Enemy/3 Final Enemy/Attack/5.png",
            "assets/img/2.Enemy/3 Final Enemy/Attack/6.png",
        ],
        hurt: [
            "assets/img/2.Enemy/3 Final Enemy/Hurt/1.png",
            "assets/img/2.Enemy/3 Final Enemy/Hurt/2.png",
            "assets/img/2.Enemy/3 Final Enemy/Hurt/3.png",
            "assets/img/2.Enemy/3 Final Enemy/Hurt/4.png",
        ],
        death: [
            "assets/img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 6.png",
            "assets/img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 7.png",
            "assets/img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 8.png",
            "assets/img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 9.png",
            "assets/img/2.Enemy/3 Final Enemy/Dead/Mesa de trabajo 2 copia 10.png",
        ],
    },

    hudIcons: {
        life: "assets/img/4. Marcadores/HUD-icons/life.png",
        poison: "assets/img/4. Marcadores/HUD-icons/poison.png",
        coins: "assets/img/4. Marcadores/HUD-icons/coins.png",
    },
});
